spring.application.name=services

spring.datasource.url=jdbc:postgresql://localhost:5432/ucab_services_db
spring.datasource.username=postgres
spring.datasource.password=Pao270906*
 
spring.data.jdbc.dialect=postgresql


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Evita que Hibernate altere o cree tablas. Solo valida que tu código coincida con la BD.
spring.jpa.hibernate.ddl-auto=validate

# Mostrar el SQL en la consola de VS Code para auditoría de desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jsreport.url=http://localhost:5488